import fs from "fs/promises";
import path from "path";
import type { FileFix } from "../agents/issue-fix.agent.js";

export interface ApplyFixesResult {
    appliedCount: number;
    modifiedFiles: string[];
    errors: string[];
}

/**
 * Applies search/replace code modifications onto the actual cloned repository files on disk.
 * 
 * @param repoPath - Absolute path to the local cloned repository directory.
 * @param fixes - Array of FileFix objects generated by the AI issue-fix agent.
 * @returns Result object containing details of applied changes.
 */
export async function applyFixes(
    repoPath: string,
    fixes: FileFix[]
): Promise<ApplyFixesResult> {
    const modifiedFiles: string[] = [];
    const errors: string[] = [];
    let appliedCount = 0;

    if (!fixes || !Array.isArray(fixes)) {
        return { appliedCount: 0, modifiedFiles: [], errors: [] };
    }

    for (const fix of fixes) {
        if (!fix.path || !Array.isArray(fix.replacements)) continue;

        const absoluteFilePath = path.join(repoPath, fix.path);

        try {
            let content = await fs.readFile(absoluteFilePath, "utf-8");
            let fileModified = false;

            for (const replacement of fix.replacements) {
                const { search, replace } = replacement;
                if (!search) continue;

                if (content.includes(search)) {
                    content = content.replace(search, replace);
                    fileModified = true;
                    appliedCount++;
                } else {
                    const errorMsg = `Search target not found in ${fix.path}: "${search.substring(0, 50)}..."`;
                    console.warn(`[applyFixes] ${errorMsg}`);
                    errors.push(errorMsg);
                }
            }

            if (fileModified) {
                await fs.writeFile(absoluteFilePath, content, "utf-8");
                modifiedFiles.push(fix.path);
                console.log(`[applyFixes] Successfully updated file on disk: ${fix.path}`);
            }
        } catch (err: any) {
            const msg = `Failed to write fix to file '${fix.path}': ${err.message}`;
            console.error(`[applyFixes] ${msg}`);
            errors.push(msg);
        }
    }

    return {
        appliedCount,
        modifiedFiles,
        errors
    };
}
